### ISSUE TITLE
Enhance Course Progress Tracking and Time Management Features

### ISSUE THREAD

**Issue by Ajitpatil92002** [daytimedrinkingclub/teacherop#17]
- [ ] 1. Track and update progress from the start of the course.
- [ ] 2. Display the average elapsed time for each submodule.
- [ ] 3. Implement a countdown timer and trigger an alert when the estimated time for completion is approaching.
- [ ] 4. Lock access to the next module or submodule until the previous one is fully completed.
